### ISSUE TITLE
Depend on num-traits 0.2 and release a new version

### ISSUE THREAD

**Issue by dvtomas** [coriolinus/lerp-rs#3]
I'm getting rid of duplicate dependencies in my project, and num-traits 0.1 vs 0.2 is one of them.

**Comment by coriolinus** [comment]
Sounds good. I'd be happy to approve a hacktoberfest PR performing the upgrade.

**Comment by coriolinus** [comment]
Closed by #4.

**Comment by dvtomas** [comment]
Thank you!
